// Words for the "Build your own Kafka" widgets. Part of KAFKA_STRINGS (as
// `build`), so the site translates them with the rest of the lab.
export const BUILD_STRINGS = {
  mine: 'Your code',
  kafka: 'Kafka’s code',
  runningOn: 'Running on: {who}',
  hints: {
    writeVarint: [
      'Zigzag first: for value ≥ 0 use value * 2, for value < 0 use -value * 2 - 1.',
      'Then loop: while the number is 128 or more, push (n % 128) + 128 and divide by 128 (Math.floor).',
      'The last byte is what is left, pushed without the top bit.',
    ],
    lookup: [
      'The index is sorted by offset. A loop over every entry passes the small tests but not the big one.',
      'Binary search: keep lo and hi; look at the middle; if its offset ≤ target, remember it and go right, else go left.',
    ],
    segmentsToDelete: [
      'Only a prefix can go: count from the oldest segment and stop at the first one you keep.',
      'By time: a segment goes when now - largestTimestamp > retentionMs.',
      'By size: keep deleting the oldest while the total minus that segment is still ≥ retentionBytes.',
      'Never count the last segment; it is the one being written. -1 turns a limit off.',
    ],
    recover: [
      'Start at position 0. A batch needs at least 12 bytes: 8 for the base offset and 4 for its length.',
      'The length is at pos + 8; the batch ends at pos + 12 + length.',
      'Stop when the end is past log.length or the CRC doesn’t match. Return where you stopped.',
    ],
  },
  fields: {
    baseOffset: [
      'Base offset',
      'Offset of the first record in the batch. Records store only their distance from it.',
    ],
    batchLength: [
      'Batch length',
      'Bytes after this field. Lets a reader jump to the next batch without parsing this one.',
    ],
    partitionLeaderEpoch: [
      'Leader epoch',
      'Which leader wrote the batch. Used to find where replicas diverged (chapter 10).',
    ],
    magic: ['Magic', 'Format version. 2 since Kafka 0.11.'],
    crc: ['CRC-32C', 'Checksum of everything after it. A torn or flipped byte makes it mismatch.'],
    attributes: [
      'Attributes',
      'Compression codec, timestamp type, transactional and control flags.',
    ],
    lastOffsetDelta: ['Last offset delta', 'Offset of the last record minus the base offset.'],
    baseTimestamp: ['Base timestamp', 'Timestamp of the first record, in milliseconds.'],
    maxTimestamp: [
      'Max timestamp',
      'Newest timestamp in the batch. Retention and the time index use it.',
    ],
    producerId: [
      'Producer id',
      'For idempotent and transactional producers (chapter 7). -1 when unused.',
    ],
    producerEpoch: ['Producer epoch', 'Fences a zombie producer with the same id. -1 when unused.'],
    baseSequence: [
      'Base sequence',
      'Sequence number of the first record, for de-duplication. -1 when unused.',
    ],
    recordCount: ['Record count', 'How many records follow.'],
    length: ['Record length', 'Varint: bytes in this record after this field.'],
    timestampDelta: [
      'Timestamp delta',
      'Varint: this record’s timestamp minus the base timestamp.',
    ],
    offsetDelta: ['Offset delta', 'Varint: this record’s offset minus the base offset.'],
    keyLength: ['Key length', 'Varint. -1 means no key (null).'],
    key: ['Key', 'The key’s bytes, UTF-8 here. Kafka never looks inside.'],
    valueLength: ['Value length', 'Varint. -1 means a null value: a tombstone.'],
    value: ['Value', 'The value’s bytes.'],
    headerCount: [
      'Header count',
      'Varint. Each header is a key and a value, both length-prefixed.',
    ],
  },
  hex: {
    label: 'Bytes of the batch, 16 per row',
    header: 'Batch header',
    record: 'Record {n}',
    pick: 'Click a byte to see which field it belongs to.',
    offset: 'Bytes {start}–{end}',
    value: 'Value: {value}',
  },
  bytes: {
    key: 'Key',
    value: 'Value',
    nullKey: 'No key',
    add: 'Add a record',
    remove: 'Remove',
    total:
      '{bytes} bytes for {n} records: {payload} bytes of keys and values, {overhead} of framing.',
    perRecord: 'Framing per record: {n} bytes.',
    flip: 'Flip a bit in the picked byte',
    unflip: 'Undo the flip',
    crcOk: 'CRC matches: a broker would accept this batch.',
    crcBad: 'CRC mismatch: a broker rejects this batch as CORRUPT_MESSAGE.',
    readBack: 'Kafka reads back: {records}',
    unreadable: 'Kafka can’t read this batch back: {error}',
  },
  index: {
    interval: 'index.interval.bytes',
    every: 'every batch',
    none: 'no index',
    target: 'Find offset',
    log: '.log file: {batches} batches, {bytes} bytes',
    file: '.index file: {entries} entries, {bytes} bytes',
    probed: 'Index entries read: {n}',
    scanned: 'Batches scanned: {n} ({bytes} bytes read)',
    found: 'Offset {offset} is in the batch at byte {position}.',
    noEntry: 'No entry ≤ {offset}, so the scan starts at byte 0.',
    started: 'Started scanning at byte {position} (entry for offset {offset}).',
    wrong:
      'Your lookup returned an entry for offset {got}, which is past {target}: the scan starts too late and misses the record.',
    threw: 'Your lookup threw: {error}',
  },
  segments: {
    produce: 'Produce 10 records',
    hour: 'Advance 1 hour',
    auto: 'Keep producing',
    segmentBytes: 'segment.bytes',
    retentionMs: 'retention.ms',
    retentionBytes: 'retention.bytes',
    forever: 'forever',
    unlimited: 'unlimited',
    hours: '{n} h',
    clock: 'Time: {time}',
    dir: 'Partition directory orders-0/',
    active: 'active',
    deleted: 'deleted',
    file: '{name}',
    size: '{bytes} B',
    range: 'offsets {from}–{to}',
    newest: 'newest record {age} ago',
    consumer: 'A slow consumer is at offset {offset}.',
    read: 'Read next',
    outOfRange:
      'OFFSET_OUT_OF_RANGE: offset {offset} was deleted (the log now starts at {start}). With auto.offset.reset=earliest it jumps to {start}; the records in between are gone.',
    jump: 'Reset to earliest',
    summary: 'Log start offset {start}, log end offset {end}, {size} bytes on disk.',
    threw: 'Your segmentsToDelete threw: {error}',
  },
  cache: {
    produce: 'Produce a batch',
    auto: 'Keep producing',
    flush: 'fsync now',
    flushEvery: 'Flush every',
    never: 'never (Kafka’s default)',
    batches: '{n} batches',
    power: 'Cut power',
    restart: 'Restart the broker',
    legend:
      'Green: on disk. Gold: only in the page cache. Red: a torn batch. Ticks: page boundaries.',
    dirty: '{dirty} of {size} bytes are only in memory.',
    lost: 'Power cut. The OS had written back some pages, not all: the file now ends mid-batch.',
    needsRecovery: 'The broker didn’t shut down cleanly. On startup it checks the log.',
    recovered: 'Recovery cut {bytes} bytes. Log end offset {before} → {after}.',
    clean: 'Recovery found nothing to cut. Log end offset {after}.',
    brokenAfter: 'Your recover kept a broken batch at byte {position}. Reading it fails: {error}',
    threw: 'Your recover threw: {error}',
    torn: 'torn',
  },
  queue: {
    queue: 'Queue',
    log: 'Log',
    mode: 'Storage',
    send: 'Send a message',
    take: '{name} takes one',
    rewind: '{name} rewinds to 0',
    empty: 'Nothing to read.',
    queueNote:
      'A queue deletes a message once someone takes it. A second reader never sees it, and nobody can read it again.',
    logNote:
      'A log keeps every message. Each reader just remembers a position (its offset), so readers don’t affect each other and can go back.',
    at: '{name}: offset {offset}',
    got: '{name} got {message}',
  },
};

export type BuildStrings = typeof BUILD_STRINGS;
