// Rasterizes Natural Earth country shapes into the pixel grid behind the
// visitor map (app/features/visits/worldmap.data.ts). Run it only to change
// the grid size or the source data:
//
//   mkdir /tmp/geo && cd /tmp/geo && npm i world-atlas@2 topojson-client@3 i18n-iso-countries@7
//   NODE_PATH=/tmp/geo/node_modules node apps/web/scripts/worldmap.mjs > apps/web/app/features/visits/worldmap.data.ts
//
// Natural Earth is public domain; world-atlas packages it as TopoJSON.
/* global process, console */
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(path.join(process.env.NODE_PATH ?? '.', 'x.js'));
const topo = require('world-atlas/countries-50m.json');
const { feature } = require('topojson-client');
const countries = require('i18n-iso-countries');

const W = 128;
const H = 56;
const NORTH = 84;
const SOUTH = -58; // Antarctica left out.
const lonAt = (x) => -180 + ((x + 0.5) * 360) / W;
const latAt = (y) => NORTH - ((y + 0.5) * (NORTH - SOUTH)) / H;
const cellOf = (lon, lat) => [
  Math.min(W - 1, Math.max(0, Math.floor(((lon + 180) / 360) * W))),
  Math.min(H - 1, Math.max(0, Math.floor(((NORTH - lat) / (NORTH - SOUTH)) * H))),
];

const NAMED = { Kosovo: 'XK', 'N. Cyprus': 'CY', Somaliland: 'SO' };
const shapes = feature(topo, topo.objects.countries)
  .features.map((f) => {
    const code = (f.id && countries.numericToAlpha2(f.id)) || NAMED[f.properties.name] || '';
    const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
    const bbox = [180, 90, -180, -90];
    for (const p of polys)
      for (const [lon, lat] of p[0]) {
        bbox[0] = Math.min(bbox[0], lon);
        bbox[1] = Math.min(bbox[1], lat);
        bbox[2] = Math.max(bbox[2], lon);
        bbox[3] = Math.max(bbox[3], lat);
      }
    return { code, polys, bbox };
  })
  .filter((s) => s.code !== 'AQ');

function inRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}
const inShape = (lon, lat, s) =>
  lon >= s.bbox[0] &&
  lon <= s.bbox[2] &&
  lat >= s.bbox[1] &&
  lat <= s.bbox[3] &&
  s.polys.some((p) => inRing(lon, lat, p[0]) && !p.slice(1).some((hole) => inRing(lon, lat, hole)));

// Each cell takes the country under most of its 3×3 sample points; it is land
// when at least two of the nine land somewhere.
const grid = Array.from({ length: H }, () => Array(W).fill(null));
for (let y = 0; y < H; y++)
  for (let x = 0; x < W; x++) {
    const votes = new Map();
    for (let sy = 0; sy < 3; sy++)
      for (let sx = 0; sx < 3; sx++) {
        const lon = lonAt(x) + ((sx - 1) * 360) / W / 3;
        const lat = latAt(y) + ((sy - 1) * (NORTH - SOUTH)) / H / 3;
        const hit = shapes.find((s) => inShape(lon, lat, s));
        if (hit) votes.set(hit.code, (votes.get(hit.code) ?? 0) + 1);
      }
    const total = [...votes.values()].reduce((a, b) => a + b, 0);
    if (total >= 2) grid[y][x] = [...votes].sort((a, b) => b[1] - a[1])[0][0];
  }

// Countries too small for any cell (Singapore, Hong Kong, island states) get
// the one cell at the middle of their biggest polygon.
const placed = new Set(grid.flat());
for (const s of shapes) {
  if (!s.code || placed.has(s.code)) continue;
  const biggest = s.polys.reduce((a, b) => (b[0].length > a[0].length ? b : a));
  const ring = biggest[0];
  const lon = ring.reduce((t, p) => t + p[0], 0) / ring.length;
  const lat = ring.reduce((t, p) => t + p[1], 0) / ring.length;
  if (lat < SOUTH || lat > NORTH) continue;
  const [x, y] = cellOf(lon, lat);
  grid[y][x] = s.code;
  placed.add(s.code);
}

const codes = [''].concat([...new Set(grid.flat().filter(Boolean))].sort());
const index = new Map(codes.map((c, i) => [c, i]));
const rows = grid.map((row) => {
  const runs = [];
  for (let x = 0; x < W;) {
    if (row[x] === null) {
      x++;
      continue;
    }
    let len = 1;
    while (x + len < W && row[x + len] === row[x]) len++;
    runs.push([x, len, index.get(row[x])].map((n) => n.toString(36)).join('.'));
    x += len;
  }
  return runs.join(' ');
});

console.log(`// Generated by scripts/worldmap.mjs from Natural Earth 1:50m. Do not edit by hand.
// ${W}×${H} cells, equirectangular, ${NORTH}°N to ${-SOUTH}°S.
export const MAP_WIDTH = ${W};
export const MAP_HEIGHT = ${H};
/** ISO 3166-1 alpha-2 codes; index 0 is land with no code. */
export const MAP_CODES = ${JSON.stringify(codes)};
/** Per row, space-separated runs of "x.length.codeIndex" in base 36. */
export const MAP_ROWS = ${JSON.stringify(rows, null, 2)};`);
