// All text on the visitor admin page. The page is only for the site's owner,
// so it stays in Chinese and outside the translated string tables.
export const VISITS_TEXT = {
  metaTitle: '访客记录',
  file: 'admin/visits',
  eyebrow: 'ADMIN',
  title: '访客记录',
  lede: '每次打开页面都会在 MySQL 里记一行：时间、IP、国家、页面、浏览器和来源。',
  unavailable: '连不上数据库，暂时看不到记录。',
  statViews: '人工访问',
  statVisitors: '不同 IP',
  statCountries: '国家和地区',
  statBots: '爬虫访问',
  mapTitle: '访客分布',
  mapDesc: '颜色越深人越多，鼠标移上去看人数。只算人，不算爬虫。',
  mapLabel: (name: string, n: number) => `${name} · ${n} 人`,
  countriesTitle: '国家和地区',
  countriesDesc: '按不同 IP 数排序，点一个只看那里来的访问。',
  unknownCountry: '未知',
  pagesTitle: '页面',
  pagesDesc: '读得最多的 20 个页面。点人数只看这一页的访问。',
  colPage: '页面',
  colViews: '次数',
  colReaders: '人数',
  colLast: '最后一次',
  logTitle: '访问记录',
  logDesc: (total: number, page: number, pages: number) =>
    `共 ${total} 条，第 ${page} / ${pages} 页。点 IP、国家或页面可以筛选。`,
  logEmpty: '没有符合条件的记录。',
  filterIp: (ip: string) => `IP ${ip}`,
  filterCountry: (name: string) => `来自 ${name}`,
  filterPath: (path: string) => `页面 ${path}`,
  clearFilter: '×',
  clearAll: '清除筛选',
  showBots: '显示爬虫',
  hideBots: '隐藏爬虫',
  bot: '爬虫',
  direct: '直接访问',
  from: (host: string) => `来自 ${host}`,
  lookup: '查归属地',
  prev: '‹ 上一页',
  next: '下一页 ›',
  pagerLabel: '翻页',
  timeZoneNote: (tz: string) => `时间按 ${tz} 显示。`,
} as const;
